main1: main1.cpp
	g++ -std=c++17 -I. \
		main1.cpp \
		ARMAS/Carpeta_combate/Armascombate.cpp \
		ARMAS/Carpeta_combate/Espada.cpp \
		ARMAS/Carpeta_items/ItemsMagicos.cpp \
		ARMAS/Carpeta_items/LibrodeHechizos.cpp \
		PERSONAJES/Magos/Magos.cpp \
		PERSONAJES/Magos/Brujo.cpp \
		PERSONAJES/Guerreros/Guerreros.cpp \
		PERSONAJES/Guerreros/Gladiador.cpp \
		-o main1

#limpio archivo inmediato
clean: 
	rm -f *.o main1